#define FN_KEY 62
#define SPACE_KEY 61
#define COMMON_THUMB_KEY SPACE_KEY

#define LEFT_THUMB_OUTER COMMON_THUMB_KEY
#define LEFT_THUMB_MIDDLE COMMON_THUMB_KEY
#define LEFT_THUMB_INNER COMMON_THUMB_KEY

#define RIGHT_THUMB_OUTER COMMON_THUMB_KEY
#define RIGHT_THUMB_MIDDLE COMMON_THUMB_KEY
#define RIGHT_THUMB_INNER COMMON_THUMB_KEY


#define TOP_LEFTPINKIE 16
#define TOP_LEFTRING 17
#define TOP_LEFTMIDDLE 18
#define TOP_LEFTINDEX 19

#define TOP_RIGHTINDEX 22
#define TOP_RIGHTMIDDLE 23
#define TOP_RIGHTRING 24
#define TOP_RIGHTPINKIE 25


#define MIDDLE_LEFTPINKIE 31
#define MIDDLE_LEFTRING 32
#define MIDDLE_LEFTMIDDLE 33
#define MIDDLE_LEFTINDEX 34

#define MIDDLE_RIGHTINDEX 37
#define MIDDLE_RIGHTMIDDLE 38
#define MIDDLE_RIGHTRING 39
#define MIDDLE_RIGHTPINKIE 40


#define BOTTOM_LEFTPINKIE 45
#define BOTTOM_LEFTRING 46
#define BOTTOM_LEFTMIDDLE 47
#define BOTTOM_LEFTINDEX 48

#define BOTTOM_RIGHTINDEX 51
#define BOTTOM_RIGHTMIDDLE 52
#define BOTTOM_RIGHTRING 53
#define BOTTOM_RIGHTPINKIE 54


#define BOTTOM_RIGHT_CORNER 67
