#define COMBOS_TIMEOUT 50
#define COMBOS_WAIT_MS 10

#define TOTAL_SWITCHES 12


#define LEFTPINKIE_COLUMN 1
#define LEFTRING_COLUMN 2
#define LEFTMIDDLE_COLUMN 3
#define LEFTINDEX_COLUMN 4

#define RIGHTINDEX_COLUMN 7
#define RIGHTMIDDLE_COLUMN 8
#define RIGHTRING_COLUMN 9
#define RIGHTPINKIE_COLUMN 10

#define TOP_ROW 0
#define MIDDLE_ROW 1
#define BOTTOM_ROW 2
#define THUMB_ROW 3
