#define LEFT_THUMB_OUTER 40
#define LEFT_THUMB_MIDDLE 39
#define LEFT_THUMB_INNER 38

#define RIGHT_THUMB_OUTER 41
#define RIGHT_THUMB_MIDDLE 42
#define RIGHT_THUMB_INNER 43


#define TOP_LEFTPINKIE 1
#define TOP_LEFTRING 2
#define TOP_LEFTMIDDLE 3
#define TOP_LEFTINDEX 4

#define TOP_RIGHTINDEX 7
#define TOP_RIGHTMIDDLE 8
#define TOP_RIGHTRING 9
#define TOP_RIGHTPINKIE 10


#define MIDDLE_LEFTPINKIE 13
#define MIDDLE_LEFTRING 14
#define MIDDLE_LEFTMIDDLE 15
#define MIDDLE_LEFTINDEX 16

#define MIDDLE_RIGHTINDEX 19
#define MIDDLE_RIGHTMIDDLE 20
#define MIDDLE_RIGHTRING 21
#define MIDDLE_RIGHTPINKIE 22


#define BOTTOM_LEFTPINKIE 25
#define BOTTOM_LEFTRING 26
#define BOTTOM_LEFTMIDDLE 27
#define BOTTOM_LEFTINDEX 28

#define BOTTOM_RIGHTINDEX 33
#define BOTTOM_RIGHTMIDDLE 34
#define BOTTOM_RIGHTRING 35
#define BOTTOM_RIGHTPINKIE 36
