#define LEFTPINKIE_COLUMN 1
#define LEFTRING_COLUMN 2
#define LEFTMIDDLE_COLUMN 3
#define LEFTINDEX_COLUMN 4
#define RIGHTINDEX_COLUMN 7
#define RIGHTMIDDLE_COLUMN 8
#define RIGHTRING_COLUMN 9
#define RIGHTPINKIE_COLUMN 10

#define TOP_ROW 0
#define MIDDLE_ROW 1
#define BOTTOM_ROW 2
#define THUMB_ROW 3

#define LEFT_THUMB_OUTER SWITCH(THUMB_ROW, 4)
#define LEFT_THUMB_MIDDLE SWITCH(THUMB_ROW, 3)
#define LEFT_THUMB_INNER SWITCH(THUMB_ROW, 2)

#define RIGHT_THUMB_OUTER SWITCH(THUMB_ROW, 7)
#define RIGHT_THUMB_MIDDLE SWITCH(THUMB_ROW, 8)
#define RIGHT_THUMB_INNER SWITCH(THUMB_ROW, 9)


#define TOP_LEFTPINKIE SWITCH(TOP_ROW, LEFTPINKIE_COLUMN)
#define TOP_LEFTRING SWITCH(TOP_ROW, LEFTRING_COLUMN)
#define TOP_LEFTMIDDLE SWITCH(TOP_ROW, LEFTMIDDLE_COLUMN)
#define TOP_LEFTINDEX SWITCH(TOP_ROW, LEFTINDEX_COLUMN)

#define TOP_RIGHTINDEX SWITCH(TOP_ROW, RIGHTINDEX_COLUMN)
#define TOP_RIGHTMIDDLE SWITCH(TOP_ROW, RIGHTMIDDLE_COLUMN)
#define TOP_RIGHTRING SWITCH(TOP_ROW, RIGHTRING_COLUMN)
#define TOP_RIGHTPINKIE SWITCH(TOP_ROW, RIGHTPINKIE_COLUMN)


#define MIDDLE_LEFTPINKIE SWITCH(MIDDLE_ROW, LEFTPINKIE_COLUMN)
#define MIDDLE_LEFTRING SWITCH(MIDDLE_ROW, LEFTRING_COLUMN)
#define MIDDLE_LEFTMIDDLE SWITCH(MIDDLE_ROW, LEFTMIDDLE_COLUMN)
#define MIDDLE_LEFTINDEX SWITCH(MIDDLE_ROW, LEFTINDEX_COLUMN)

#define MIDDLE_RIGHTINDEX SWITCH(MIDDLE_ROW, RIGHTINDEX_COLUMN)
#define MIDDLE_RIGHTMIDDLE SWITCH(MIDDLE_ROW, RIGHTMIDDLE_COLUMN)
#define MIDDLE_RIGHTRING SWITCH(MIDDLE_ROW, RIGHTRING_COLUMN)
#define MIDDLE_RIGHTPINKIE SWITCH(MIDDLE_ROW, RIGHTPINKIE_COLUMN)


#define BOTTOM_LEFTPINKIE SWITCH(BOTTOM_ROW, LEFTPINKIE_COLUMN)
#define BOTTOM_LEFTRING SWITCH(BOTTOM_ROW, LEFTRING_COLUMN)
#define BOTTOM_LEFTMIDDLE SWITCH(BOTTOM_ROW, LEFTMIDDLE_COLUMN)
#define BOTTOM_LEFTINDEX SWITCH(BOTTOM_ROW, LEFTINDEX_COLUMN)

#define BOTTOM_RIGHTINDEX SWITCH(BOTTOM_ROW, RIGHTINDEX_COLUMN)
#define BOTTOM_RIGHTMIDDLE SWITCH(BOTTOM_ROW, RIGHTMIDDLE_COLUMN)
#define BOTTOM_RIGHTRING SWITCH(BOTTOM_ROW, RIGHTRING_COLUMN)
#define BOTTOM_RIGHTPINKIE SWITCH(BOTTOM_ROW, RIGHTPINKIE_COLUMN)
